const fs = require('fs');
const path = require('path');

// Synchronously read the content of our package.json file
const metadata = fs.readFileSync('./package.json', 'utf8');

// We need to extract the package name to rename our widget PHP configuration file
const {name} = JSON.parse(metadata);

// Rename the file from widget.php to the corresponding name
// build/wiget.php is the file generated by Mustache (see package.json's widget:config script)
fs.rename('build/widget.php', `build/${name}.php`, err => {
  if (err) {
    console.log('ERROR: ' + err);
  }
});
